// Generated by CoffeeScript 1.8.0

/*
1) Run this application
$ node examples/basic.js

2) Simulate ifttt XMLRPC calls
$ node examples/call.js

3) Check the results
$ curl http://127.0.0.1:3001/
 */

(function() {
  var api, app, config, connect, ifttt, server, store;

  config = require('./config');

  connect = require('connect');

  ifttt = require('../lib/index');

  store = [];

  api = ifttt(config);

  api.on('save_post', function(data) {
    console.log("received data", data);
    return store.push(data);
  });

  app = function(req, res) {
    console.log("serve received data");
    return res.end(JSON.stringify(store));
  };

  server = connect();

  server.use(api);

  server.use(app);

  server.listen(config.port);

  console.log("Listening on http://" + config.host + ":" + config.port);

}).call(this);
